/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;

/**
 *
 * @author ANTHONY LAWRENCE
 */
public class Hospitals extends javax.swing.JFrame {

    /**
     * Creates new form Hospitals
     */
       Connection con;
    PreparedStatement pst;
    ResultSet rs;
    private Object Connections;
    private Component frmlogin;
    //establish connection
  PreparedStatement statement; //execute sql statement more of optimised
  Statement st;//execute sql statement less of optimised
  String cs; //holding path of the database
  String user;//username for the database
  String password;//password for the database
  String query;
  String records;
  Boolean bnext = false;
  Boolean bprevious = true;
    public Hospitals() {
        initComponents();
                          con = null;
    st = null;
    statement = null;
    
    cs = "jdbc:mysql://localhost:3306/tour_and_travel_information_management_system";
    user = "root";
    password = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtcontact = new javax.swing.JTextField();
        txtlocation = new javax.swing.JTextField();
        txtsecurity = new javax.swing.JTextField();
        txtinterest = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("H:\\java pics\\LL.png")); // NOI18N
        jLabel1.setText("HOSPITALS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Hospital location :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 102, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Hospital name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 71, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Area of interest :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 164, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Hospital contacts :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 133, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Security Contacts :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 195, -1, -1));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 69, 129, 25));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setText("Save a hospital");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 150, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Delete hospital");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, 150, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("H:\\java pics\\exit.png")); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Next record");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, 150, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Previous record");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, 150, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Back to menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, 150, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Search a hospital");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, -1));
        getContentPane().add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 131, 129, 25));
        getContentPane().add(txtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 100, 129, 25));
        getContentPane().add(txtsecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 193, 129, 25));
        getContentPane().add(txtinterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 162, 129, 25));

        jLabel7.setForeground(new java.awt.Color(51, 0, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("H:\\java pics\\WE.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
      // code for save button 
        String s1 = txtname.getText();
        String s2= txtlocation.getText();
        String s3 = txtcontact.getText();
        String s4 = txtinterest.getText();
        String s5 = txtsecurity.getText();

        
        try {
            Class.forName("com.mysql.jdbc.Driver"); //Register the driver
            
            con=DriverManager.getConnection(cs,user,password); // Maaking connection
            
            st =con.createStatement();// Creating stmt
            
            //insert query stmt
            query= "INSERT INTO hospital (hospital_name,hospital_location,hospital_contacts, Things_of_interest_toi_name, Security_contacts_security_issue)VALUES('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"')";
            
            st.executeUpdate(query); //st to execute the query
            
         JOptionPane.showMessageDialog(null,"Record Saved"); // to show pop up message
            
           txtname.setText("");
            txtlocation.setText("");
            txtcontact.setText("");
            txtinterest.setText("");
            txtsecurity.setText("");
            txtname.requestFocus();//Request Focus
            
            
        }
        catch (SQLException | ClassNotFoundException ex){
            ex.printStackTrace();
    }
        finally{
            
            try{
                if(st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch(SQLException ex){
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //code to take us back to menu
        Menu mi = new Menu();
        mi.show();
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //code to search of find a record from the database
            
         try {
    
    Class.forName("com.mysql.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    query = "SELECT * FROM hospital WHERE  hospital_name = '"+txtname.getText()+"'";
    
    ResultSet rs = st.executeQuery(query);
    if(rs.first()){
       txtname.setText(rs.getString("hosptial_name")); 
       txtlocation.setText(rs.getString("hospital_location"));
       txtcontact.setText(rs.getString("hospital_contact"));
      txtinterest.setText(rs.getString("Area of interest"));
      txtsecurity.setText(rs.getString("Security contacts"));
    }
    else{
        JOptionPane.showMessageDialog(null,"Record not found");
       txtname.setText("");
        txtname.requestFocus();
    }
         
}
catch (SQLException | ClassNotFoundException ex){
    ex.printStackTrace();
}

finally{
    
    try{
        if(st != null)
        {
            st.close();
        }
        if(con != null){
            con.close();
        }
    }
        catch (SQLException ex){
                ex.printStackTrace();
                }
    }

        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // code for the delete button
        int answer = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete?","confirm",JOptionPane.YES_NO_OPTION);
        
    if(answer == YES_OPTION){
     try {
    
    Class.forName("com.mysql.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    query = "DELETE FROM hospital WHERE hospital_name='"+txtname.getText()+"'";
    
     if(st.executeUpdate(query) == 1){
         JOptionPane.showMessageDialog(null,"Record with hospital_name '"+txtname.getText()+"'deleted");
         
     }
     else if(st.executeUpdate(query) == 0){
         JOptionPane.showMessageDialog(null,"Record with Country_name: '"+txtname.getText()+"'does not exist");
     }
  }
     
catch (     SQLException | ClassNotFoundException ex){
    ex.printStackTrace();
}

finally{
    
    try{
        if(st != null)
        {
            st.close();
        }
        if(con != null){
            con.close();
        }
    }
        catch (SQLException ex){
                ex.printStackTrace();
                }
    }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       // code for the next button
        
        try {
   
    Class.forName("com.mysql.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    query = "SELECT * FROM hospital ";
    if(!bnext){
      rs = st.executeQuery(query);  
       rs.first();
   
      txtname.setText(rs.getString("hospital_name"));
               txtlocation.setText(rs.getString("hospital_location"));
               txtcontact.setText(rs.getString("hospital_contacts"));
               txtinterest.setText(rs.getString("Area of interest"));
               txtsecurity.setText(rs.getString("Security contacts"));
       
       bnext = true;
    }
    else if(rs.next()){
        
   txtname.setText(rs.getString("hospital_name"));
               txtlocation.setText(rs.getString("hospital_location"));
               txtcontact.setText(rs.getString("hospital_contact"));
               txtinterest.setText(rs.getString("Area of interest"));
               txtsecurity.setText(rs.getString("Security contacts"));
     
     bnext = true;
       
    }
 
}
catch (SQLException | ClassNotFoundException ex){
    ex.printStackTrace();
}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       // code for previous button to show rhe previous record
         try {
   
    Class.forName("com.mysql.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    query = "SELECT * FROM hospital ";
   
    if(!bprevious){
      rs = st.executeQuery(query);  
       rs.last();
   
       txtname.setText(rs.getString("hospital_name"));
               txtlocation.setText(rs.getString("hospital_location"));

       bprevious = true;
    }
    else if(rs.previous()){
        
      txtname.setText(rs.getString("hospital_name"));
              txtlocation.setText(rs.getString("hospital_location"));
              
     bnext = true;
       
    }
    
    
       
}
catch (SQLException | ClassNotFoundException ex){
    ex.printStackTrace();
}

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         //CODE FOR EXIT BUTTON
        JFrame Componentfrmlogin = new JFrame("EXIT");
        Component frmlogin = null;
        if(JOptionPane.showConfirmDialog(frmlogin, "Are you sure?", "exit", 
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospitals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtinterest;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsecurity;
    // End of variables declaration//GEN-END:variables
}
